Repository subspacecommunity/subspace, pull requests merged in 2020-07, with the labels that each got.

#116 Disable devices limit until better implementation
  cmd/subspace/handlers.go
Labels: bug

#107 Support multiarch
  Dockerfile
  Dockerfile.build
  Makefile
  README.md
  multi-arch-manifest.yaml
  scripts/dockerfiles/386.dockerfile
  scripts/dockerfiles/amd64.dockerfile
  scripts/dockerfiles/arm32v5.dockerfile
  scripts/dockerfiles/arm32v6.dockerfile
  scripts/dockerfiles/arm32v7.dockerfile
  scripts/dockerfiles/arm64v8.dockerfile
Labels: Large, enhancement

#111 Feature/totp default admin
  cmd/subspace/config.go
  cmd/subspace/handlers.go
  cmd/subspace/main.go
  cmd/subspace/web.go
  go.mod
  go.sum
  web/templates/settings.html
  web/templates/signin.html
Labels: enhancement

#124 updated post_push to generate manifest dynamically
  scripts/dockerfiles/hooks/post_push
  scripts/dockerfiles/multi-arch-manifest.yaml
Labels: enhancement

#125 adding static latest dockerhub tag
  scripts/dockerfiles/hooks/post_push
Labels: enhancement
