Repository subspacecommunity/subspace, pull requests merged in 2020-05, with the labels that each got.

#53 adding PR and ISSUE templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#48 Removing quotes in docker-compose and add systemd-resolved notice
  README.md
Labels: documentation, enhancement

#44 Allow disabling masquerade
  entrypoint.sh
Labels: enhancement

#39 Move Running docker to use Alpine Linux
  Dockerfile
  Makefile
  entrypoint.sh
Labels: enhancement

#40 (Chore) Upgrade GoMods
  go.mod
  go.sum
Labels: enhancement

#50 Add contributing section
  .github/CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#71 Check for iptables binary before exec
  entrypoint.sh
Labels: bug

#42 Code cleanup (golangci-lint)
  config.go
  handlers.go
  main.go
Labels: enhancement
