Repository subspacecommunity/subspace, pull requests merged in 2020-06, with the labels that each got.

#75 Docker Alpine - Fix Forward
  Dockerfile
  README.md
  bin/my_init
  entrypoint.sh
Labels: Large, enhancement

#89 Docs/slack info
  README.md
Labels: documentation, enhancement

#99 source envvars before service run
  entrypoint.sh
Labels: bug

#100 Enhancement/theme selection
  .gitignore
  README.md
  entrypoint.sh
  main.go
  templates/configure.html
  templates/forgot.html
  templates/header.html
  templates/help.html
  templates/index.html
  templates/profile/connect.html
  templates/profile/delete.html
  templates/settings.html
  templates/signin.html
  templates/user/delete.html
  templates/user/edit.html
  web.go
Labels: enhancement

#102 Fixing issues picked up by Sonarcloud
  README.md
  email/footer.html
  email/header.html
  templates/footer.html
  templates/header.html
  templates/profile/connect.html
  templates/settings.html
Labels: documentation, enhancement
